# Generated by Django 4.2.3 on 2023-07-12 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alarm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('device', models.CharField(max_length=100)),
                ('status', models.BooleanField(choices=[(True, 'Enabled'), (False, 'Disabled')], default=True)),
                ('single', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')])),
                ('alarm_type', models.CharField(default='alarm', max_length=100)),
                ('monday', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')])),
                ('tuesday', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')])),
                ('wednesday', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')])),
                ('thursday', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')])),
                ('friday', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')])),
                ('saturday', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')])),
                ('sunday', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')])),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('device_type', models.CharField(choices=[('solenoid', 'Solenoid')], default='solenoid', max_length=100)),
                ('status', models.CharField(default='OFF', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ScheduledTimer',
            fields=[
                ('alarm_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='device_scheduler.alarm')),
                ('end_time', models.TimeField()),
            ],
            bases=('device_scheduler.alarm',),
        ),
    ]
