# Generated by Django 4.2.3 on 2023-07-14 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('device_scheduler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alarm',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='device_scheduler.device'),
        ),
    ]
