# Generated by Django 4.2.3 on 2023-07-17 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device_scheduler', '0002_alter_alarm_device'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scheduledtimer',
            old_name='end_time',
            new_name='duration_minutes',
        ),
        migrations.AlterField(
            model_name='alarm',
            name='friday',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True),
        ),
        migrations.AlterField(
            model_name='alarm',
            name='monday',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True),
        ),
        migrations.AlterField(
            model_name='alarm',
            name='saturday',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True),
        ),
        migrations.AlterField(
            model_name='alarm',
            name='sunday',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True),
        ),
        migrations.AlterField(
            model_name='alarm',
            name='thursday',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True),
        ),
        migrations.AlterField(
            model_name='alarm',
            name='tuesday',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True),
        ),
        migrations.AlterField(
            model_name='alarm',
            name='wednesday',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True),
        ),
    ]
