# Generated by Django 4.2.3 on 2023-07-17 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('device_scheduler', '0003_rename_end_time_scheduledtimer_duration_minutes_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scheduledtimer',
            old_name='duration_minutes',
            new_name='duration_minutes_seconds',
        ),
    ]
